Update v1.yaml
chariot-giving/chariot-openapi pull request #15
Opened 2023-12-18 19:14 UTC by salo1serfati

Ticket here: https://www.notion.so/givechariot/API-Doc-Changes-b97a3d062eca406ca6c5f63db8b059ea?pvs=4

1. Update `Get Nonprofit` endpoint: 1. If a suborganization is found, it should be returned in this call. @Matthew Magaldi and Salo to flesh out where this will be. 2. If a Nonprofit is not **registered** with Chariot, this should return 404 Not Found.
2. Update `Create Nonprofit` API endpoint. 1. Make the email field optional based on a workflow config. 2. If the Nonprofit they are trying to create is not a 501c3 or pub_78 verified, then throw a **422 Unprocessable Content** with a reason 1.  `The EIN is not a 501c3` 2. `The EIN is not Publication 78 verified` 3. @Matthew Magaldi and Salo to flesh out what this does behind the scenes
3. Update `Create Connect` endpoint 1. Add an optional parameter `suborganization` that allows you to create a Connect for a sub-organization
4. Update `Create Grant` endpoint. 1. Add parameter `applicationFeeAmount` which is the amount in cents that the FP wants to charge for this grant. This fee in addition to Chariot’s fee cannot exceed 5% of the grants amount.
5. Update `Grant` object to return the new set of grant statues
6. Update `Connect` object 1. Add boolean `isDafpayNetwork` parameter, specifying that grants from this connect will go through the DAFpay network. 2. To better explain the userFriendlyId
7. Add Manual grants endpoint to the api docs.

2023-12-21 17:35 UTC, magaldima requested changes
@salo1serfati left a few comments. we also may need to revisit the grant statuses enum too

2023-12-21 17:35 UTC, magaldima commented on specs/v1.yaml
> +        When integrating this API, it's useful to make a call to the GET v1/nonprofit/{ein} API first to check if it exists prior to creating it.
we can remove this line since this should be renamed to "Get or Create"

2023-12-21 17:35 UTC, magaldima commented on specs/v1.yaml
> +  /v1/grants/unintegrated:
i personally would like unintegrated grants to live as a separate resource in our APIs: e.g. `unintegrated-grants` so this becomes: `v1/unintegrated-grants`

2023-12-21 17:35 UTC, magaldima commented on specs/v1.yaml
> +  /v1/grants/unintegrated/{id}:
working off comment above i think this should be: `/v1/unintegrated-grants/{id}`

2023-12-21 17:35 UTC, magaldima commented on specs/v1.yaml
> +    Suborganizations:
the model should be singular, e.g. `Suborganization` and you should make sure to update the reference above

2023-12-21 17:35 UTC, magaldima commented on specs/v1.yaml
> +        isDafpayNetwork:
this needs to be moved to the Organization object

2023-12-21 17:35 UTC, magaldima commented on specs/v1.yaml
> +          description: A flag to indicate if grants made via this Connect will be processed through the DAFpay Network.
description should be updated to be specific to the organization now

2023-12-21 17:35 UTC, magaldima commented on specs/v1.yaml
> +                  is deducted. The sum of Chariot's fee and the applicationFeeAmount cannot exceed 5% of the grant's amount.
is this validation done upfront by our server before submitting the grant? if so, what does this API fail with in the case that this happens, e.g. 400 status code? it's useful to clearly write out the error cases

2023-12-22 16:30 UTC, salo1serfati commented
> This parameter specifies the fee your platform

Do you think it's worthwhile to expose isDAFpayNetwork on the API? It probably makes sense to abstract that concept away from the FundraisingPlatform. For them, every payment is made via the DAFpayNetwork.

2024-01-16 20:51 UTC, magaldima requested changes
left a few minor comments

2024-01-16 20:51 UTC, magaldima commented on specs/v1.yaml
> +          description: Often refered to as the "Chariot ID", this is the ID that will be included in the payment from the DAF provider.
refered -> referred . also might need to escape the quotes around Chariot ID

2024-01-16 20:51 UTC, magaldima commented on specs/v1.yaml
> +          example: "Chariot Fee"
this should just be "Chariot'

2024-01-16 20:51 UTC, magaldima commented on specs/v1.yaml
> +          description: Often refered to as the "Chariot ID", this is the ID that will be included in the payment from the DAF provider.
also, are we adding `trackingId` to the grant API?

2024-01-16 21:28 UTC, magaldima commented
also we need to merge conflicts

2024-01-16 21:34 UTC, magaldima submitted a review, later dismissed

2024-01-16 21:37 UTC, magaldima approved these changes

2024-01-17 19:18 UTC, magaldima commented
almost there, a few more linter errors:
```
/github/workspace/specs/v1.yaml
 824:20  error  oas3-valid-schema-example  "example" property type must be string                components.schemas.UnintegratedGrant.properties.userFriendlyId.example
 876:17  error  no-$ref-siblings           $ref must not be placed next to any other properties  components.schemas.UnintegratedGrant.properties.address.type
 878:24  error  no-$ref-siblings           $ref must not be placed next to any other properties  components.schemas.UnintegratedGrant.properties.address.description
```

2024-01-17 20:30 UTC, magaldima approved these changes

2024-01-22 18:55 UTC, merged